# Generated by Django 3.2.4 on 2022-09-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
